web:
  build: .docker/web
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./docroot:/var/www/docroot
  links:
    - fpm
db:
  image: mysql
  ports:
    - 3306:3306
  environment:
    - MYSQL_ROOT_PASSWORD=admin123
    - MYSQL_DATABASE=drupal8
    - MYSQL_USER=drupal
    - MYSQL_PASSWORD=thisisawesome
fpm:
  build: .docker/fpm
  volumes:
    - ./docroot:/var/www/docroot
  ports:
    - 9000
  links:
    - db
cli:
 build: .docker/cli
 volumes:
   - ./docroot:/var/www/docroot
 links:
   - db
   - web
