web:
  image: socketwench/druplet-web
  ports:
    - "80:80"
  volumes:
    - ./docroot:/var/www/html/
  links:
    - db
db:
  image: mysql
  ports:
    - 3306:3306
  environment:
    - MYSQL_ROOT_PASSWORD=admin123
    - MYSQL_DATABASE=drupal8
    - MYSQL_USER=drupal
    - MYSQL_PASSWORD=thisisawesome
cli:
  build: .docker/cli
  volumes:
    - ./docroot:/var/www
  links:
    - db
    - web
