web:
  build: .docker/web
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./docroot:/var/www/docroot
  links:
    - db
    - cli
db:
  image: mysql
  ports:
    - 3306:3306
  environment:
    - MYSQL_ROOT_PASSWORD=admin123
    - MYSQL_DATABASE=drupal8
    - MYSQL_USER=drupal
    - MYSQL_PASSWORD=thisisawesome
cli:
  build: .docker/cli
  volumes:
    - ./docroot:/var/www/docroot
  links:
    - db
