web:
  build: .docker/web
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./docroot:/var/www/docroot
  links:
    - db
    - fpm
db:
  image: mysql
  ports:
    - 3306:3306
  environment:
    - MYSQL_ROOT_PASSWORD=admin123
    - MYSQL_DATABASE=drupal8
    - MYSQL_USER=drupal
    - MYSQL_PASSWORD=thisisawesome
fpm:
  image: php:fpm
  volumes:
    - ./docroot:/var/www/docroot
  ports:
    - 9000
#cli:
#  build: .docker/cli
#  volumes:
#    - ./docroot:/var/www/docroot
#  links:
#    - db
#    - web
